### ISSUE TITLE
Compilation with Mac OSX

### ISSUE THREAD

**Issue by JHP-bah** [FingerJetFXOSE/FingerJetFXOSE#3]
ake -C src/libFRFXLL 
make -C src/libFRFXLL 
c++ -O2 -I../algorithm -I../../include -I../../src/include -I../../../ExternalDependencies/STL/STLport-5.2.1/stlport -fno-exceptions -fno-rtti -fno-stack-protector -fPIC -DFRFXLL_MAJOR=5 -DFRFXLL_MINOR=2 -DFRFXLL_REVISION=0 -DFRFXLL_BUILD=0   -c -o FRFXLLCreateContext.o FRFXLLCreateContext.cpp
0  clang 0x0000000100c57bb2 main + 12932498
Stack dump:
0.  Program arguments: /usr/bin/clang -cc1 -triple x86_64-apple-macosx10.8.0 -emit-obj -disable-free -disable-llvm-verifier -main-file-name FRFXLLCreateContext.cpp -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 136 -coverage-file /usr/local/FingerJetFXOSE-master/src/libFRFXLL/src/libFRFXLL/FRFXLLCreateContext.o -resource-dir /usr/bin/../lib/clang/4.2 -D FRFXLL_MAJOR=5 -D FRFXLL_MINOR=2 -D FRFXLL_REVISION=0 -D FRFXLL_BUILD=0 -I ../algorithm -I ../../include -I ../../src/include -I ../../../ExternalDependencies/STL/STLport-5.2.1/stlport -fmodule-cache-path /var/folders/1s/2lh2c7ls1l9cbnthjkp9dh_40000gn/T/clang-module-cache -O2 -fdeprecated-macro -fdebug-compilation-dir /usr/local/FingerJetFXOSE-master -ferror-limit 19 -fmessage-length 206 -mstackrealign -fblocks -fno-rtti -fobjc-runtime=macosx-10.8.0 -fobjc-dispatch-method=mixed -fobjc-default-synthesize-properties -fdiagnostics-show-option -fcolor-diagnostics -o FRFXLLCreateContext.o -x c++ FRFXLLCreateContext.cpp 
1.  ../algorithm/extract_minutia.h:288:42: current parser token ';'
2.  ../algorithm/extract_minutia.h:42:1: parsing namespace 'FingerJetFxOSE'
3.  ../algorithm/extract_minutia.h:43:1: parsing namespace 'FpRecEngineImpl'
4.  ../algorithm/extract_minutia.h:44:1: parsing namespace 'Embedded'
5.  ../algorithm/extract_minutia.h:45:1: parsing namespace 'FeatureExtractionImpl'
6.  ../algorithm/extract_minutia.h:270:155: parsing function body 'extract_minutia'
7.  ../algorithm/extract_minutia.h:270:155: in compound statement ('{}')
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)
Target: x86_64-apple-darwin12.5.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 

---

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/1s/2lh2c7ls1l9cbnthjkp9dh_40000gn/T/FRFXLLCreateContext-ZzZd5F.cpp
clang: note: diagnostic msg: /var/folders/1s/2lh2c7ls1l9cbnthjkp9dh_40000gn/T/FRFXLLCreateContext-ZzZd5F.sh
clang: note: diagnostic msg: 

---

make[2]: **\* [FRFXLLCreateContext.o] Error 254
make[1]: **\* [src/libFRFXLL] Error 2
make: **\* [src/libFRFXLL] Error 2

**Comment by RLessmann** [comment]
changed build tool to cmale, but require xcode 9. later xcode versions will not build 32 bit libs
