### ISSUE TITLE
Unit tests seem to be failing

### ISSUE THREAD

**Issue by azihassan** [FingerJetFXOSE/FingerJetFXOSE#8]
Running `make check` causes TestCreateFeatureSet(), TestCreateFeatureSetInPlace(), TestCreateFeatureSetFromRaw() and TestCreateFeatureSetInPlaceFromRaw() to fail with the message "data differs from expectedFeatureSetin size : 486 != 438".

After modifying the inner code to bypass the size difference and display the first 10 differences in the data, I got the following output :

`
make -C src/libFRFXLL check
make[1]: Entering directory `/var/www/html/crossmatch/FingerJetFXOSE-master/src/libFRFXLL'
make -C src/libFRFXLL check
make[2]: Entering directory `/var/www/html/crossmatch/FingerJetFXOSE-master/src/libFRFXLL/src/libFRFXLL'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/var/www/html/crossmatch/FingerJetFXOSE-master/src/libFRFXLL/src/libFRFXLL'
make -C samples/FRFXLLSample check
make[2]: Entering directory `/var/www/html/crossmatch/FingerJetFXOSE-master/src/libFRFXLL/samples/FRFXLLSample'
./../../bin/FRFXLLSample
Starting tests.
Version 5.2.0.0
..
FRFXLLSample.c:220: error : data differs from expectedFeatureSetin size : 486 != 438
 first 10 differences:
data[0x000b] = 0xe6 != 0xb6
data[0x001b] = 0x4c != 0x44
data[0x01b4] = 0x80 != 0x00
data[0x01b5] = 0x8c != 0x00
0x46, 0x4d, 0x52, 0x00, 0x20, 0x32, 0x30, 0x00, 0x00, 0x00, 0x01, 0xe6, 0x00, 0x00, 0x00, 0xc0, 
0x01, 0x5e, 0x00, 0xc5, 0x00, 0xc5, 0x01, 0x00, 0x00, 0x00, 0x56, 0x4c, 0x80, 0x5c, 0x01, 0x4f, 
0x3d, 0x5e, 0x80, 0x5d, 0x00, 0xcb, 0x89, 0x5d, 0x40, 0x4b, 0x01, 0x44, 0xc0, 0x5c, 0x40, 0x67, 
0x01, 0x37, 0x43, 0x59, 0x40, 0x75, 0x00, 0x56, 0x82, 0x57, 0x80, 0x0b, 0x01, 0x25, 0xaf, 0x54, 
0x80, 0x5d, 0x01, 0x32, 0xc3, 0x52, 0x40, 0x7a, 0x01, 0x29, 0x4d, 0x4f, 0x40, 0x42, 0x01, 0x48, 
0x45, 0x4f, 0x80, 0x1a, 0x01, 0x1f, 0xb1, 0x4d, 0x80, 0x95, 0x00, 0x5c, 0x7d, 0x4b, 0x80, 0x9d, 
0x01, 0x2c, 0x47, 0x49, 0x80, 0x74, 0x00, 0x37, 0xf7, 0x46, 0x80, 0x7d, 0x00, 0xbf, 0x77, 0x46, 
0x40, 0x8f, 0x01, 0x2a, 0xc0, 0x46, 0x40, 0x6f, 0x00, 0x56, 0xff, 0x45, 0x40, 0x9c, 0x00, 0x99, 
0x69, 0x45, 0x80, 0x14, 0x00, 0xf5, 0xa3, 0x44, 0x40, 0x65, 0x01, 0x43, 0xb7, 0x44, 0x40, 0x98, 
0x01, 0x53, 0xb5, 0x44, 0x40, 0x0b, 0x01, 0x3d, 0xb5, 0x44, 0x40, 0x15, 0x01, 0x4e, 0xc1, 0x43, 
0x80, 0xb3, 0x00, 0x43, 0x6a, 0x43, 0x80, 0x2d, 0x00, 0xa2, 0x95, 0x42, 0x40, 0xb0, 0x00, 0x98, 
0x64, 0x41, 0x40, 0x6b, 0x01, 0x00, 0xe8, 0x41, 0x40, 0x6d, 0x00, 0xf2, 0x85, 0x41, 0x80, 0x91, 
0x00, 0xee, 0x65, 0x40, 0x80, 0xa6, 0x01, 0x2d, 0xb5, 0x40, 0x40, 0x3f, 0x01, 0x0c, 0xab, 0x40, 
0x40, 0x33, 0x00, 0xa5, 0x09, 0x3f, 0x40, 0x3f, 0x01, 0x19, 0xb3, 0x3f, 0x80, 0xa3, 0x00, 0x57, 
0xe0, 0x3f, 0x80, 0x67, 0x00, 0x5b, 0x91, 0x3f, 0x80, 0x3f, 0x01, 0x00, 0xa4, 0x3f, 0x80, 0x1f, 
0x00, 0xe8, 0x1b, 0x3e, 0x40, 0x8c, 0x00, 0xf5, 0xd7, 0x3e, 0x40, 0x90, 0x01, 0x14, 0x4d, 0x3e, 
0x40, 0x5a, 0x00, 0x2f, 0x84, 0x3e, 0x40, 0x7f, 0x00, 0xce, 0x79, 0x3e, 0x40, 0x0e, 0x00, 0xf5, 
0xa5, 0x3e, 0x40, 0xb0, 0x00, 0xfb, 0x52, 0x3e, 0x40, 0x62, 0x00, 0x1c, 0x72, 0x3d, 0x80, 0x9d, 
0x00, 0x22, 0xe7, 0x3d, 0x40, 0x11, 0x01, 0x2c, 0x3b, 0x3d, 0x40, 0x7b, 0x01, 0x4e, 0x39, 0x3d, 
0x40, 0x91, 0x01, 0x55, 0x3b, 0x3d, 0x80, 0x68, 0x01, 0x56, 0x3b, 0x3d, 0x80, 0x57, 0x00, 0x21, 
0x79, 0x3c, 0x40, 0x98, 0x00, 0xf8, 0x58, 0x3c, 0x80, 0x7a, 0x01, 0x18, 0x58, 0x3c, 0x80, 0x5a, 
0x01, 0x21, 0xbd, 0x3c, 0x40, 0x13, 0x00, 0xfc, 0xa7, 0x3c, 0x80, 0x48, 0x01, 0x1a, 0xac, 0x3c, 
0x40, 0xb8, 0x01, 0x07, 0xd5, 0x3b, 0x40, 0x6b, 0x00, 0x23, 0x76, 0x3b, 0x80, 0x6f, 0x01, 0x2c, 
0xc5, 0x3b, 0x40, 0x9b, 0x01, 0x39, 0x3d, 0x3b, 0x40, 0x5d, 0x00, 0x37, 0x7d, 0x3a, 0x80, 0xa4, 
0x00, 0x49, 0x5d, 0x3a, 0x80, 0x96, 0x00, 0x91, 0x7d, 0x3a, 0x80, 0x4e, 0x00, 0x63, 0x10, 0x39, 
0x80, 0xa4, 0x00, 0xbd, 0xe9, 0x39, 0x40, 0x26, 0x00, 0xcc, 0x96, 0x39, 0x80, 0x69, 0x00, 0xd4, 
0xfb, 0x39, 0x80, 0x83, 0x00, 0xf4, 0xcd, 0x39, 0x40, 0x50, 0x01, 0x3f, 0xc3, 0x39, 0x40, 0x86, 
0x00, 0xfb, 0x5e, 0x39, 0x80, 0x8c, 0x01, 0x0f, 0x50, 0x39, 0x80, 0x75, 0x00, 0x11, 0xf5, 0x38, 
0x40, 0x77, 0x00, 0x8c, 0xfc, 0x38, 0x40, 0x9e, 0x00, 0x37, 0xe5, 0x37, 0x40, 0x4e, 0x00, 0x5e, 
0x06, 0x37, 0x40, 0xa3, 0x00, 0x75, 0x7b, 0x37, 0x40, 0xb0, 0x01, 0x42, 0x43, 0x37, 0x80, 0xa9, 
0x01, 0x43, 0xbc, 0x37, 0x00, 0x00, 
.
FRFXLLSample.c:238: error : data differs from expectedFeatureSetin size : 486 != 438
 first 10 differences:
data[0x000b] = 0xe6 != 0xb6
data[0x001b] = 0x4c != 0x44
data[0x01b4] = 0x80 != 0x00
data[0x01b5] = 0x8c != 0x00
0x46, 0x4d, 0x52, 0x00, 0x20, 0x32, 0x30, 0x00, 0x00, 0x00, 0x01, 0xe6, 0x00, 0x00, 0x00, 0xc0, 
0x01, 0x5e, 0x00, 0xc5, 0x00, 0xc5, 0x01, 0x00, 0x00, 0x00, 0x56, 0x4c, 0x80, 0x5c, 0x01, 0x4f, 
0x3d, 0x5e, 0x80, 0x5d, 0x00, 0xcb, 0x89, 0x5d, 0x40, 0x4b, 0x01, 0x44, 0xc0, 0x5c, 0x40, 0x67, 
0x01, 0x37, 0x43, 0x59, 0x40, 0x75, 0x00, 0x56, 0x82, 0x57, 0x80, 0x0b, 0x01, 0x25, 0xaf, 0x54, 
0x80, 0x5d, 0x01, 0x32, 0xc3, 0x52, 0x40, 0x7a, 0x01, 0x29, 0x4d, 0x4f, 0x40, 0x42, 0x01, 0x48, 
0x45, 0x4f, 0x80, 0x1a, 0x01, 0x1f, 0xb1, 0x4d, 0x80, 0x95, 0x00, 0x5c, 0x7d, 0x4b, 0x80, 0x9d, 
0x01, 0x2c, 0x47, 0x49, 0x80, 0x74, 0x00, 0x37, 0xf7, 0x46, 0x80, 0x7d, 0x00, 0xbf, 0x77, 0x46, 
0x40, 0x8f, 0x01, 0x2a, 0xc0, 0x46, 0x40, 0x6f, 0x00, 0x56, 0xff, 0x45, 0x40, 0x9c, 0x00, 0x99, 
0x69, 0x45, 0x80, 0x14, 0x00, 0xf5, 0xa3, 0x44, 0x40, 0x65, 0x01, 0x43, 0xb7, 0x44, 0x40, 0x98, 
0x01, 0x53, 0xb5, 0x44, 0x40, 0x0b, 0x01, 0x3d, 0xb5, 0x44, 0x40, 0x15, 0x01, 0x4e, 0xc1, 0x43, 
0x80, 0xb3, 0x00, 0x43, 0x6a, 0x43, 0x80, 0x2d, 0x00, 0xa2, 0x95, 0x42, 0x40, 0xb0, 0x00, 0x98, 
0x64, 0x41, 0x40, 0x6b, 0x01, 0x00, 0xe8, 0x41, 0x40, 0x6d, 0x00, 0xf2, 0x85, 0x41, 0x80, 0x91, 
0x00, 0xee, 0x65, 0x40, 0x80, 0xa6, 0x01, 0x2d, 0xb5, 0x40, 0x40, 0x3f, 0x01, 0x0c, 0xab, 0x40, 
0x40, 0x33, 0x00, 0xa5, 0x09, 0x3f, 0x40, 0x3f, 0x01, 0x19, 0xb3, 0x3f, 0x80, 0xa3, 0x00, 0x57, 
0xe0, 0x3f, 0x80, 0x67, 0x00, 0x5b, 0x91, 0x3f, 0x80, 0x3f, 0x01, 0x00, 0xa4, 0x3f, 0x80, 0x1f, 
0x00, 0xe8, 0x1b, 0x3e, 0x40, 0x8c, 0x00, 0xf5, 0xd7, 0x3e, 0x40, 0x90, 0x01, 0x14, 0x4d, 0x3e, 
0x40, 0x5a, 0x00, 0x2f, 0x84, 0x3e, 0x40, 0x7f, 0x00, 0xce, 0x79, 0x3e, 0x40, 0x0e, 0x00, 0xf5, 
0xa5, 0x3e, 0x40, 0xb0, 0x00, 0xfb, 0x52, 0x3e, 0x40, 0x62, 0x00, 0x1c, 0x72, 0x3d, 0x80, 0x9d, 
0x00, 0x22, 0xe7, 0x3d, 0x40, 0x11, 0x01, 0x2c, 0x3b, 0x3d, 0x40, 0x7b, 0x01, 0x4e, 0x39, 0x3d, 
0x40, 0x91, 0x01, 0x55, 0x3b, 0x3d, 0x80, 0x68, 0x01, 0x56, 0x3b, 0x3d, 0x80, 0x57, 0x00, 0x21, 
0x79, 0x3c, 0x40, 0x98, 0x00, 0xf8, 0x58, 0x3c, 0x80, 0x7a, 0x01, 0x18, 0x58, 0x3c, 0x80, 0x5a, 
0x01, 0x21, 0xbd, 0x3c, 0x40, 0x13, 0x00, 0xfc, 0xa7, 0x3c, 0x80, 0x48, 0x01, 0x1a, 0xac, 0x3c, 
0x40, 0xb8, 0x01, 0x07, 0xd5, 0x3b, 0x40, 0x6b, 0x00, 0x23, 0x76, 0x3b, 0x80, 0x6f, 0x01, 0x2c, 
0xc5, 0x3b, 0x40, 0x9b, 0x01, 0x39, 0x3d, 0x3b, 0x40, 0x5d, 0x00, 0x37, 0x7d, 0x3a, 0x80, 0xa4, 
0x00, 0x49, 0x5d, 0x3a, 0x80, 0x96, 0x00, 0x91, 0x7d, 0x3a, 0x80, 0x4e, 0x00, 0x63, 0x10, 0x39, 
0x80, 0xa4, 0x00, 0xbd, 0xe9, 0x39, 0x40, 0x26, 0x00, 0xcc, 0x96, 0x39, 0x80, 0x69, 0x00, 0xd4, 
0xfb, 0x39, 0x80, 0x83, 0x00, 0xf4, 0xcd, 0x39, 0x40, 0x50, 0x01, 0x3f, 0xc3, 0x39, 0x40, 0x86, 
0x00, 0xfb, 0x5e, 0x39, 0x80, 0x8c, 0x01, 0x0f, 0x50, 0x39, 0x80, 0x75, 0x00, 0x11, 0xf5, 0x38, 
0x40, 0x77, 0x00, 0x8c, 0xfc, 0x38, 0x40, 0x9e, 0x00, 0x37, 0xe5, 0x37, 0x40, 0x4e, 0x00, 0x5e, 
0x06, 0x37, 0x40, 0xa3, 0x00, 0x75, 0x7b, 0x37, 0x40, 0xb0, 0x01, 0x42, 0x43, 0x37, 0x80, 0xa9, 
0x01, 0x43, 0xbc, 0x37, 0x00, 0x00, 
.
FRFXLLSample.c:260: error : data differs from expectedFeatureSetin size : 486 != 438
 first 10 differences:
data[0x000b] = 0xe6 != 0xb6
data[0x001b] = 0x4c != 0x44
data[0x01b4] = 0x80 != 0x00
data[0x01b5] = 0x8c != 0x00
0x46, 0x4d, 0x52, 0x00, 0x20, 0x32, 0x30, 0x00, 0x00, 0x00, 0x01, 0xe6, 0x00, 0x00, 0x00, 0xc0, 
0x01, 0x5e, 0x00, 0xc5, 0x00, 0xc5, 0x01, 0x00, 0x00, 0x00, 0x56, 0x4c, 0x80, 0x5c, 0x01, 0x4f, 
0x3d, 0x5e, 0x80, 0x5d, 0x00, 0xcb, 0x89, 0x5d, 0x40, 0x4b, 0x01, 0x44, 0xc0, 0x5c, 0x40, 0x67, 
0x01, 0x37, 0x43, 0x59, 0x40, 0x75, 0x00, 0x56, 0x82, 0x57, 0x80, 0x0b, 0x01, 0x25, 0xaf, 0x54, 
0x80, 0x5d, 0x01, 0x32, 0xc3, 0x52, 0x40, 0x7a, 0x01, 0x29, 0x4d, 0x4f, 0x40, 0x42, 0x01, 0x48, 
0x45, 0x4f, 0x80, 0x1a, 0x01, 0x1f, 0xb1, 0x4d, 0x80, 0x95, 0x00, 0x5c, 0x7d, 0x4b, 0x80, 0x9d, 
0x01, 0x2c, 0x47, 0x49, 0x80, 0x74, 0x00, 0x37, 0xf7, 0x46, 0x80, 0x7d, 0x00, 0xbf, 0x77, 0x46, 
0x40, 0x8f, 0x01, 0x2a, 0xc0, 0x46, 0x40, 0x6f, 0x00, 0x56, 0xff, 0x45, 0x40, 0x9c, 0x00, 0x99, 
0x69, 0x45, 0x80, 0x14, 0x00, 0xf5, 0xa3, 0x44, 0x40, 0x65, 0x01, 0x43, 0xb7, 0x44, 0x40, 0x98, 
0x01, 0x53, 0xb5, 0x44, 0x40, 0x0b, 0x01, 0x3d, 0xb5, 0x44, 0x40, 0x15, 0x01, 0x4e, 0xc1, 0x43, 
0x80, 0xb3, 0x00, 0x43, 0x6a, 0x43, 0x80, 0x2d, 0x00, 0xa2, 0x95, 0x42, 0x40, 0xb0, 0x00, 0x98, 
0x64, 0x41, 0x40, 0x6b, 0x01, 0x00, 0xe8, 0x41, 0x40, 0x6d, 0x00, 0xf2, 0x85, 0x41, 0x80, 0x91, 
0x00, 0xee, 0x65, 0x40, 0x80, 0xa6, 0x01, 0x2d, 0xb5, 0x40, 0x40, 0x3f, 0x01, 0x0c, 0xab, 0x40, 
0x40, 0x33, 0x00, 0xa5, 0x09, 0x3f, 0x40, 0x3f, 0x01, 0x19, 0xb3, 0x3f, 0x80, 0xa3, 0x00, 0x57, 
0xe0, 0x3f, 0x80, 0x67, 0x00, 0x5b, 0x91, 0x3f, 0x80, 0x3f, 0x01, 0x00, 0xa4, 0x3f, 0x80, 0x1f, 
0x00, 0xe8, 0x1b, 0x3e, 0x40, 0x8c, 0x00, 0xf5, 0xd7, 0x3e, 0x40, 0x90, 0x01, 0x14, 0x4d, 0x3e, 
0x40, 0x5a, 0x00, 0x2f, 0x84, 0x3e, 0x40, 0x7f, 0x00, 0xce, 0x79, 0x3e, 0x40, 0x0e, 0x00, 0xf5, 
0xa5, 0x3e, 0x40, 0xb0, 0x00, 0xfb, 0x52, 0x3e, 0x40, 0x62, 0x00, 0x1c, 0x72, 0x3d, 0x80, 0x9d, 
0x00, 0x22, 0xe7, 0x3d, 0x40, 0x11, 0x01, 0x2c, 0x3b, 0x3d, 0x40, 0x7b, 0x01, 0x4e, 0x39, 0x3d, 
0x40, 0x91, 0x01, 0x55, 0x3b, 0x3d, 0x80, 0x68, 0x01, 0x56, 0x3b, 0x3d, 0x80, 0x57, 0x00, 0x21, 
0x79, 0x3c, 0x40, 0x98, 0x00, 0xf8, 0x58, 0x3c, 0x80, 0x7a, 0x01, 0x18, 0x58, 0x3c, 0x80, 0x5a, 
0x01, 0x21, 0xbd, 0x3c, 0x40, 0x13, 0x00, 0xfc, 0xa7, 0x3c, 0x80, 0x48, 0x01, 0x1a, 0xac, 0x3c, 
0x40, 0xb8, 0x01, 0x07, 0xd5, 0x3b, 0x40, 0x6b, 0x00, 0x23, 0x76, 0x3b, 0x80, 0x6f, 0x01, 0x2c, 
0xc5, 0x3b, 0x40, 0x9b, 0x01, 0x39, 0x3d, 0x3b, 0x40, 0x5d, 0x00, 0x37, 0x7d, 0x3a, 0x80, 0xa4, 
0x00, 0x49, 0x5d, 0x3a, 0x80, 0x96, 0x00, 0x91, 0x7d, 0x3a, 0x80, 0x4e, 0x00, 0x63, 0x10, 0x39, 
0x80, 0xa4, 0x00, 0xbd, 0xe9, 0x39, 0x40, 0x26, 0x00, 0xcc, 0x96, 0x39, 0x80, 0x69, 0x00, 0xd4, 
0xfb, 0x39, 0x80, 0x83, 0x00, 0xf4, 0xcd, 0x39, 0x40, 0x50, 0x01, 0x3f, 0xc3, 0x39, 0x40, 0x86, 
0x00, 0xfb, 0x5e, 0x39, 0x80, 0x8c, 0x01, 0x0f, 0x50, 0x39, 0x80, 0x75, 0x00, 0x11, 0xf5, 0x38, 
0x40, 0x77, 0x00, 0x8c, 0xfc, 0x38, 0x40, 0x9e, 0x00, 0x37, 0xe5, 0x37, 0x40, 0x4e, 0x00, 0x5e, 
0x06, 0x37, 0x40, 0xa3, 0x00, 0x75, 0x7b, 0x37, 0x40, 0xb0, 0x01, 0x42, 0x43, 0x37, 0x80, 0xa9, 
0x01, 0x43, 0xbc, 0x37, 0x00, 0x00, 
.
FRFXLLSample.c:283: error : data differs from expectedFeatureSetin size : 486 != 438
 first 10 differences:
data[0x000b] = 0xe6 != 0xb6
data[0x001b] = 0x4c != 0x44
data[0x01b4] = 0x80 != 0x00
data[0x01b5] = 0x8c != 0x00
0x46, 0x4d, 0x52, 0x00, 0x20, 0x32, 0x30, 0x00, 0x00, 0x00, 0x01, 0xe6, 0x00, 0x00, 0x00, 0xc0, 
0x01, 0x5e, 0x00, 0xc5, 0x00, 0xc5, 0x01, 0x00, 0x00, 0x00, 0x56, 0x4c, 0x80, 0x5c, 0x01, 0x4f, 
0x3d, 0x5e, 0x80, 0x5d, 0x00, 0xcb, 0x89, 0x5d, 0x40, 0x4b, 0x01, 0x44, 0xc0, 0x5c, 0x40, 0x67, 
0x01, 0x37, 0x43, 0x59, 0x40, 0x75, 0x00, 0x56, 0x82, 0x57, 0x80, 0x0b, 0x01, 0x25, 0xaf, 0x54, 
0x80, 0x5d, 0x01, 0x32, 0xc3, 0x52, 0x40, 0x7a, 0x01, 0x29, 0x4d, 0x4f, 0x40, 0x42, 0x01, 0x48, 
0x45, 0x4f, 0x80, 0x1a, 0x01, 0x1f, 0xb1, 0x4d, 0x80, 0x95, 0x00, 0x5c, 0x7d, 0x4b, 0x80, 0x9d, 
0x01, 0x2c, 0x47, 0x49, 0x80, 0x74, 0x00, 0x37, 0xf7, 0x46, 0x80, 0x7d, 0x00, 0xbf, 0x77, 0x46, 
0x40, 0x8f, 0x01, 0x2a, 0xc0, 0x46, 0x40, 0x6f, 0x00, 0x56, 0xff, 0x45, 0x40, 0x9c, 0x00, 0x99, 
0x69, 0x45, 0x80, 0x14, 0x00, 0xf5, 0xa3, 0x44, 0x40, 0x65, 0x01, 0x43, 0xb7, 0x44, 0x40, 0x98, 
0x01, 0x53, 0xb5, 0x44, 0x40, 0x0b, 0x01, 0x3d, 0xb5, 0x44, 0x40, 0x15, 0x01, 0x4e, 0xc1, 0x43, 
0x80, 0xb3, 0x00, 0x43, 0x6a, 0x43, 0x80, 0x2d, 0x00, 0xa2, 0x95, 0x42, 0x40, 0xb0, 0x00, 0x98, 
0x64, 0x41, 0x40, 0x6b, 0x01, 0x00, 0xe8, 0x41, 0x40, 0x6d, 0x00, 0xf2, 0x85, 0x41, 0x80, 0x91, 
0x00, 0xee, 0x65, 0x40, 0x80, 0xa6, 0x01, 0x2d, 0xb5, 0x40, 0x40, 0x3f, 0x01, 0x0c, 0xab, 0x40, 
0x40, 0x33, 0x00, 0xa5, 0x09, 0x3f, 0x40, 0x3f, 0x01, 0x19, 0xb3, 0x3f, 0x80, 0xa3, 0x00, 0x57, 
0xe0, 0x3f, 0x80, 0x67, 0x00, 0x5b, 0x91, 0x3f, 0x80, 0x3f, 0x01, 0x00, 0xa4, 0x3f, 0x80, 0x1f, 
0x00, 0xe8, 0x1b, 0x3e, 0x40, 0x8c, 0x00, 0xf5, 0xd7, 0x3e, 0x40, 0x90, 0x01, 0x14, 0x4d, 0x3e, 
0x40, 0x5a, 0x00, 0x2f, 0x84, 0x3e, 0x40, 0x7f, 0x00, 0xce, 0x79, 0x3e, 0x40, 0x0e, 0x00, 0xf5, 
0xa5, 0x3e, 0x40, 0xb0, 0x00, 0xfb, 0x52, 0x3e, 0x40, 0x62, 0x00, 0x1c, 0x72, 0x3d, 0x80, 0x9d, 
0x00, 0x22, 0xe7, 0x3d, 0x40, 0x11, 0x01, 0x2c, 0x3b, 0x3d, 0x40, 0x7b, 0x01, 0x4e, 0x39, 0x3d, 
0x40, 0x91, 0x01, 0x55, 0x3b, 0x3d, 0x80, 0x68, 0x01, 0x56, 0x3b, 0x3d, 0x80, 0x57, 0x00, 0x21, 
0x79, 0x3c, 0x40, 0x98, 0x00, 0xf8, 0x58, 0x3c, 0x80, 0x7a, 0x01, 0x18, 0x58, 0x3c, 0x80, 0x5a, 
0x01, 0x21, 0xbd, 0x3c, 0x40, 0x13, 0x00, 0xfc, 0xa7, 0x3c, 0x80, 0x48, 0x01, 0x1a, 0xac, 0x3c, 
0x40, 0xb8, 0x01, 0x07, 0xd5, 0x3b, 0x40, 0x6b, 0x00, 0x23, 0x76, 0x3b, 0x80, 0x6f, 0x01, 0x2c, 
0xc5, 0x3b, 0x40, 0x9b, 0x01, 0x39, 0x3d, 0x3b, 0x40, 0x5d, 0x00, 0x37, 0x7d, 0x3a, 0x80, 0xa4, 
0x00, 0x49, 0x5d, 0x3a, 0x80, 0x96, 0x00, 0x91, 0x7d, 0x3a, 0x80, 0x4e, 0x00, 0x63, 0x10, 0x39, 
0x80, 0xa4, 0x00, 0xbd, 0xe9, 0x39, 0x40, 0x26, 0x00, 0xcc, 0x96, 0x39, 0x80, 0x69, 0x00, 0xd4, 
0xfb, 0x39, 0x80, 0x83, 0x00, 0xf4, 0xcd, 0x39, 0x40, 0x50, 0x01, 0x3f, 0xc3, 0x39, 0x40, 0x86, 
0x00, 0xfb, 0x5e, 0x39, 0x80, 0x8c, 0x01, 0x0f, 0x50, 0x39, 0x80, 0x75, 0x00, 0x11, 0xf5, 0x38, 
0x40, 0x77, 0x00, 0x8c, 0xfc, 0x38, 0x40, 0x9e, 0x00, 0x37, 0xe5, 0x37, 0x40, 0x4e, 0x00, 0x5e, 
0x06, 0x37, 0x40, 0xa3, 0x00, 0x75, 0x7b, 0x37, 0x40, 0xb0, 0x01, 0x42, 0x43, 0x37, 0x80, 0xa9, 
0x01, 0x43, 0xbc, 0x37, 0x00, 0x00, 
..
Done
make[2]: Leaving directory `/var/www/html/crossmatch/FingerJetFXOSE-master/src/libFRFXLL/samples/FRFXLLSample'
make[1]: Leaving directory `/var/www/html/crossmatch/FingerJetFXOSE-master/src/libFRFXLL'
`

**Comment by RLessmann** [comment]
changed test to use a buffer with limited size, otherwise fingerjet fx will extract up to 255 minutiae, but the test set contains less data
