### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by vilyansky** [FingerJetFXOSE/FingerJetFXOSE#9]
Can't build library. Make stopped with:
<builtin>: recipe for target 'FRFXLLCreateFeatureSetInPlaceFromRaw.o' failed
make[2]: *** [FRFXLLCreateFeatureSetInPlaceFromRaw.o] Error 1
make[2]: Leaving directory '/home/super_pypsik/Downloads/FingerJetFXOSE/src/libFRFXLL/src/libFRFXLL'
Makefile:50: recipe for target 'src/libFRFXLL' failed
make[1]: *** [src/libFRFXLL] Error 2
make[1]: Leaving directory '/home/super_pypsik/Downloads/FingerJetFXOSE/src/libFRFXLL'
Makefile:50: recipe for target 'src/libFRFXLL' failed
make: *** [src/libFRFXLL] Error 2

**Comment by vilyansky** [comment]
gcc --version
gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0

**Comment by vilyansky** [comment]
make --version
GNU Make 4.1

Any ideas?

**Comment by RLessmann** [comment]
changed build tools to cmake
